### ISSUE TITLE
Using bioperl-live with travis-ci

### ISSUE THREAD

**Issue by rvosa** [bioperl/bioperl-live#112]
Hi,

I'm trying to set up a .travis.yml for a repository that needs bioperl-live (and bioperl-run) but when I give 'BioPerl' as a dependency in this repo's Makefile.PL travis tries to get all the dependencies that CPAN's version of bioperl-live suggests, including DB_File - which fails. Is there some other way that this can be done?

Thanks,

Rutger

**Comment by tsibley** [comment]
DB_File probably fails because the vanilla Travis VM doesn't have appropriate `dbm` development headers installed, or possibly are even missing the shared libs.  You can configure your `.travis.yml` to install those using `apt-get`.  This is just a guess, of course, because you didn't provide any error output that could be used to diagnose the problem.

I highly suspect it's not specific to BioPerl, though.

**Comment by rvosa** [comment]
I worked around it by cloning the bioperl repos and adding them to
PERL5LIB: https://github.com/naturalis/supersmart/blob/master/.travis.yml


Op Sat, 18 Apr 2015 om 04:21 schreef Thomas Sibley <notifications@github.com
