### ISSUE TITLE
File open for 'command |' not working

### ISSUE THREAD

**Issue by nds** [bioperl/bioperl-live#117]
In older versions of Bio/Root/IO.pm the following line was used to open files:

open ($fh,$file) || $self->throw("Could not open $file: $!");

In newer versions, the following line is used with $mode defaulting to "<".

open $fh, $mode, $file or $self->throw("Could not $action file '$file': $!");

So, for example, when we use:

$fastq_obj =  Bio::SeqIO->new( -file => "gunzip -c myfile.gz |" , -format => 'Fastq');

This becomes:

open $fh, '<', 'gunzip -c myfile.gz |'

causing the following error:

Could not read file 'gunzip -c myfile.gz |': No such file or directory

**Comment by fjossandon** [comment]
In my humble opinion this is not a bug, the "-file" argument is expecting a filename not a command, which should be handled separately with a system(). Besides, that compressed "myfile.gz" could contain multiple files and the SeqIO only can handle one. Also allowing this would cause trouble for filenames that contains whitespaces, since how could it differentiate if the passed argument is a file or a command??

**Comment by nds** [comment]
There are some examples in the documentation showing the use of 'command |' like in http://www.bioperl.org/wiki/HOWTO:SeqIO but I agree that passing commands into -file can get really messy. I've fixed this usage on our end. Thank you for responding so quickly.

**Comment by fjossandon** [comment]
Oh, I didn't know about those examples, thanks for pointing them out!

**Comment by hyphaltip** [comment]
We have a -fh option for root::io where you make the fh and pass it to the
constructor. That is the the better way to do that I think.

**Comment by fjossandon** [comment]
That sounds more reasonable than "-file". Then the examples at http://www.bioperl.org/wiki/HOWTO:SeqIO could be rewritten, but I can't login into the wiki and I receive this message: "OpenID 2.0 was replaced by OpenID Connect, and since April 20, 2015, no longer works for Google Accounts. OpenID 2.0 support was shut down in order to focus on the newer open standard OpenID Connect, which provides greater security for your account."

Can somebody with Wiki access update those examples (or update the OpenID)??

**Comment by majensen** [comment]
I think this issue with the wiki should be prioritized. I could help, if I could
login....

On Wed, Jul 01, 2015 at 4:23 PM, Francisco J. Ossandon < notifications@github.com [notifications@github.com] > wrote:
That sounds more reasonable than "-file". Then the examples at http://www.bioperl.org/wiki/HOWTO:SeqIO
[http://www.bioperl.org/wiki/HOWTO:SeqIO] could be rewritten, but I can't login into the wiki and I receive this message:
"OpenID 2.0 was replaced by OpenID Connect, and since April 20, 2015, no longer
works for Google Accounts. OpenID 2.0 support was shut down in order to focus on
the newer open standard OpenID Connect, which provides greater security for your
account."

Can somebody with Wiki access update those examples (or update the OpenID)??

—
Reply to this email directly or view it on GitHub
[https://github.com/bioperl/bioperl-live/issues/117#issuecomment-117714153] .[https://github.com/notifications/beacon/AAFAmZPbJ1uipkqW7AfnBh1ROhnPi80Nks5oY_1-gaJpZM4FP0he.gif]

**Comment by hyphaltip** [comment]
I'm also unable to login - we need someone to do some wiki fixes and then
move the wiki to read the docs or elsewhere pronto!

Jason Stajich
jason.stajich@gmail.com
