### ISSUE TITLE
RFC: Bio::PDBx?

### ISSUE THREAD

**Issue by sillitoe** [bioperl/bioperl-live#204]
I've been going through a spring clean of some of our local code (at [CATH](http://www.cathdb.info)) - trying to push some of our libraries as independent modules on GitHub (and possibly out to CPAN where appropriate).

There's a fair amount of stuff I could potentially package up as independent libraries and push out - one example is a set of modules that will fetch and parse basic PDB header info from XML data (from local files and as a webservice):

https://github.com/sillitoe/bio-pdbx

I've moved this tentatively to the `Bio::` namespace, but the code is completely independent of BioPerl (in terms of root objects, logging, documentation style, testing, dependencies, etc).

Interested on any thoughts on:

a) this module
b) general plans for integrating (independent) code into BioPerl

**Comment by cjfields** [comment]
@sillitoe even though we have a lot of modules occupying the `Bio::*` space, I don't think we can lay claim to all of it to be frank (it's too broad to be under one project).  For a good example and a very good project see @rvosa and https://github.com/rvosa/bio-phylo

Re: integration: my initial suggestions:

1.  Add optional support in your code which uses the PDB XML parser to convert to BioPerl Bio::Structure objects (Bio::Structure is a section of code where you could help out, it's not seen much care).  In this case there is no need to add directly to the core code.  There are a few modules [that do this](http://deps.cpantesters.org/depended-on-by.pl?module=Bio::Root::Root).
2. Add core support for Moo or Moose.  I started down this road myself but have invested more of my (vanishingly small) time in Perl 6 lately.  

I do think it's worth keeping your code separate and released on CPAN, primarily so that (1) it's not dependent on the core release cycle, which can be glacial, and (2) that we (the Bioperl core devs) do not become the primary maintainers for the code, which then switches the maintenance burden to us.

**Comment by sillitoe** [comment]
All sounds very sensible - thanks.

  1. I'll look into making Bio::Structure an optional extra then push to CPAN. Currently this only parses info from PDB headers (e.g. rather than the 3D coordinates from ATOM records). Wouldn't hurt to consider that compatibility for future use though.
  1. Support for Moo(se) sounds like a great long term goal. I'm guessing that may require a full code immersion for a sustained period of time to avoid breaking things, slowing things down, tests, docs. Happy to help where I can, but realistically I also only get bite-size chunks of dev time these days. Welcome to tag me on a specific issue - I'll help if I can.
