### ISSUE TITLE
master is failing installation and build

### ISSUE THREAD

**Issue by hlapp** [bioperl/bioperl-live#240]
It seems that the Travis CI build off of `master` is currently failing. The first error was introduced when Perl v5.26 was added:
```
do "_build/build_params" failed, '.' is no longer in @INC; did you mean do "./_build/build_params"? at -e line 1.
Can't use an undefined value as an ARRAY reference at -e line 1.
```
See <https://travis-ci.org/bioperl/bioperl-live/jobs/259101067#L4727-L4728>

It is failing widespread and with many failures since the merging of #237 (to fix bug #236): https://travis-ci.org/bioperl/bioperl-live/builds/259101066

I don't know what the `COVERAGE=N TEST_PARTITION=M` environment settings are for, but apparently if they are set and the value of `TEST_PARTITION` is greater than 2 (1 still fails), then the tests succeed. (It looks like that's a very limited set of tests though.)

I assume that it's because of these failures that the [Docker image rebuild for BioPerl off of master](https://hub.docker.com/r/bioperl/bioperl/builds/b5x33uf2ox4jryw4rddmqrm/) has been failing too. That doesn't make the bioperl/bioperl:latest Docker image unavailable, but at this point it is not sync'ed up with current `master`, because the current `master` fails to install.

**Comment by zmughal** [comment]
Perl 5.26 is a build failure, not a test failure. That will require separate handling. It should have been done on a branch and pull request  and made to pass on its own before being added to the master branch.

The `COVERAGE=1 TEST_PARTITION=N` part is to split the tests in separate groups so that a full code coverage can be run on the entire test suite and not reach the TravisCI timeout of 49 minutes.

The `TEST_PARTITION=1` is failing because that one partition contains the tests that are failing. The other Perl's (besides 5.26) fail on that same group of tests. After doing a revert on commit <https://github.com/bioperl/bioperl-live/commit/1bdddd33347e89bb12fd1dcf9740688629568f6b>, it is clear that those test failures are because of that commit.

I'll try to propose some PRs that fix both these issues separately.

**Comment by zmughal** [comment]
The build failure for Perl 5.26.0 on Travis has nothing to with bioperl itself and is instead an issue with the travis-perl/helpers script we are using. I have put in a [PR](https://github.com/travis-perl/helpers/pull/53) that when merged should fix that issue.

**Comment by bosborne** [comment]
Actually did that commit on a branch, but deleted the branch. My mistake. Unfortunately can not see this error when I upgrade to 5.26, so your fixes will be appreciated.

**Comment by hlapp** [comment]
Fixed, thanks @zmughal !
