### ISSUE TITLE
Travis-CI problems

### ISSUE THREAD

**Issue by cjfields** [bioperl/bioperl-live#260]
The latest Travis runs are failing, needs delving into.

https://travis-ci.org/bioperl/bioperl-live

**Comment by zmughal** [comment]
Odd. It looks like it ran out of resources on all those builds at the time. That can usually be fixed by restarting the build manually.

I ran the same config on my fork of bioperl here and the build passed <https://travis-ci.org/zmughal/bioperl-live/builds/325927398>. I expect it should pass here as well.

**Comment by zmughal** [comment]
The [latest commit](https://github.com/bioperl/bioperl-live/commit/39e65a49eed88c4c39eaabc09ac531201eb0e067) on master is [passing on Travis CI now](https://travis-ci.org/bioperl/bioperl-live/builds/332623093?utm_source=github_status&utm_medium=notification).

Seems like it was just a temporary issue and this issue can now be closed, right?

**Comment by cjfields** [comment]
@zmughal Yes, not sure what caused it (maybe a corrupt image)
