### ISSUE TITLE
edit synopsis for Bio::PopGen::Utilities.pm?

### ISSUE THREAD

**Issue by jayoung** [bioperl/bioperl-live#275]
hi again,

another tiny suggestion - the docs for Bio::PopGen::Utilities are bit confusing right now.  Lines 33 and 34 in the synopsis currently read: 
```
# get the synonymous sites from the alignemt only as the 'genotypes'
# for the population

```
But it seems like using 
-site_model => 'cod' 
still gets all sites, synonymous and non-synonymous, not just synonymous as the doc currently suggests. Maybe those lines should read something line this: 
`# treat the alignment as protein coding sequence - each marker will be a codon rather than an individual nucleotide position
`

thanks,

Janet

**Comment by cjfields** [comment]
Paging @hyphaltip

**Comment by cjfields** [comment]
As a note, @carandraug is moving the PopGen modules into a separate repository for separate release.

**Comment by hyphaltip** [comment]
That change sounds good to the docs - it’s treating it like coding seq is best description. Feel free to make a PR? Not sure when I’ll get to any edits myself but prob after the migrate to the new repo I’ll try to look.

I never integrated a way to get syn-only because it requires defining the reference and never developed a way to tackle this. Could just instead provide 1st,2nd,or 3rd pos (or some combo)

Jason Stajich, PhD
jasonstajich.phd@gmail.com

**Comment by carandraug** [comment]
> [...] Not sure when I’ll get to any edits myself but prob after the migrate to the new repo I’ll try to look.

This already happened.  Please see https://github.com/bioperl/Bio-PopGen

**Comment by hyphaltip** [comment]
This issue was moved to bioperl/Bio-PopGen#1
