### ISSUE TITLE
Bio::Procedural won't install

### ISSUE THREAD

**Issue by threepistons** [bioperl/bioperl-live#354]
**Given:** Ubuntu 18.04 on Azure Lab Services and CPANm from https://cpanmin.us/.  Output of `cpanm --version` follows:
``` Perl
student@ML-RefVm-558285:~$ cpanm --version
cpanm (App::cpanminus) version 1.7044 (/usr/local/bin/cpanm)
perl version 5.026001 (/usr/bin/perl)

  %Config:
    archname=x86_64-linux-gnu-thread-multi
    installsitelib=/usr/local/share/perl/5.26.1
    installsitebin=/usr/local/bin
    installman1dir=/usr/share/man/man1
    installman3dir=/usr/share/man/man3
    sitearchexp=/usr/local/lib/x86_64-linux-gnu/perl/5.26.1
    sitelibexp=/usr/local/share/perl/5.26.1
    vendorarch=/usr/lib/x86_64-linux-gnu/perl5/5.26
    vendorlibexp=/usr/share/perl5
    archlibexp=/usr/lib/x86_64-linux-gnu/perl/5.26
    privlibexp=/usr/share/perl/5.26
  %ENV:
  @INC:
    FatPacked::94794177631760=HASH(0x5636fd48d610)
    /etc/perl
    /usr/local/lib/x86_64-linux-gnu/perl/5.26.1
    /usr/local/share/perl/5.26.1
    /usr/lib/x86_64-linux-gnu/perl5/5.26
    /usr/share/perl5
    /usr/lib/x86_64-linux-gnu/perl/5.26
    /usr/share/perl/5.26
    /usr/local/lib/site_perl
    /usr/lib/x86_64-linux-gnu/perl-base
```

**When I:** run ` cpanm --sudo Bio::Perl`

**I get:**
```
--> Working on Bio::Perl
Fetching http://www.cpan.org/authors/id/C/CJ/CJFIELDS/Bio-Procedural-1.7.4.tar.gz ... OK
Configuring Bio-Procedural-1.7.4 ... OK
Building and testing Bio-Procedural-1.7.4 ... FAIL
! Installing Bio::Perl failed. See /home/student/.cpanm/work/1610913441.21814/build.log for details. Retry with --force to force install it.
```
Running `cpanm --sudo Bio::Procedural` gives:
```
--> Working on Bio::Procedural
Fetching http://www.cpan.org/authors/id/C/CJ/CJFIELDS/Bio-Procedural-1.7.4.tar.gz ... OK
Configuring Bio-Procedural-1.7.4 ... OK
Building and testing Bio-Procedural-1.7.4 ... FAIL
! Installing Bio::Procedural failed. See /home/student/.cpanm/work/1610913458.21910/build.log for details. Retry with --force to force install it.
```
[Attached contents](https://github.com/bioperl/bioperl-live/files/5826751/bio-procedural-fail-log.txt) of /home/student/.cpanm/work/1610913458.21910/build.log

**I expected:** Perl::Bio to install without issues.

**Comment by threepistons** [comment]
`cpanm --sudo cpanm --sudo Module::Build` updated Module::Build but didn't allow Bio::Procedural to install, I still get the same test failures.

**Comment by threepistons** [comment]
Workaround, assuming that the workaround is not by-design installation technique:
`cpanm --sudo BioPerl` **without** double-colons.
Then `cpanm --sudo Bio::Procedural` installs without any problems.

**Comment by carandraug** [comment]
I'm pretty sure the issue is that you had an old version of the "BioPerl" distribution (which was updated when you `cpanm BioPerl`).

1. The `Bio::Perl` module is part of the "Bio-Procedural" distribution (it is not part of the "BioPerl" distribution). That is why when you `cpanm Bio::Perl` it installs "Bio-Procedural" (you ask to install a module so cpanm installs the distribution that includes the module)
2. "Bio-Procedural" distribution is dependent on the "BioPerl" distribution but not any specific version of it. My guess is that you already had an older "BioPerl" installed.
3. The version of BioPerl you have has the bug you found. That bug has already been fixed.
4. When you manually installed the "BioPerl" distribution (with `cpanm BioPerl`) you upgraded it to the latest version which has the issue fixed.
5. When you then installed the "Bio-Procedural" distribution it worked fine.

**Comment by threepistons** [comment]
I was following the [instructions for installing Prokka](https://github.com/tseemann/prokka#ubuntudebianmint), which don't work.
